namespace: 0ta2
name: ansible_roles
version: 1.0.1
readme: README.md
authors:
- 0ta2 <example@domain.com>
description: Ansible Rools.
license:
- MIT License
license_file: ''
tags:
- collection
dependencies: {}
repository: https://github.com/0ta2/ansible_roles
documentation: https://github.com/0ta2/ansible_roles
homepage: https://github.com/0ta2/ansible_roles
issues: https://github.com/0ta2/ansible_roles/issues
